[manager]
show_hidden = true

[opener]
play = [
    { run = 'vlc "$@"', orphan = true, for = "unix" }
]
edit = [
	{ run = 'code "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
